services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ensky
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwertyuiop
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME: ensky
      DB_USER: root
      DB_PASSWORD: qwertyuiop
      DB_HOST: postgres
    ports:
      - '3002:3000'
      - '9230:9230'
    depends_on:
      postgres:
        condition: service_healthy

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://node-app:3000
    ports:
      - '3001:3000'
    depends_on:
      - node-app